### ISSUE TITLE
Change the page title

### ISSUE THREAD

**Issue by vitorsouzaalmeida** [vit0rr/crud-react#10]
Currently, the page title is "Vite App". Change to "React crud"

**Comment by Mount-Blanc** [comment]
I'd like to work on this issue.

**Comment by vitorsouzaalmeida** [comment]
> I'd like to work on this issue.

Nice!
Send a pull request

**Comment by hrutik7** [comment]
Is this still open?

**Comment by vitorsouzaalmeida** [comment]
> Is this still open?

Yeap,
I saw your PR, merged at https://github.com/vit0rr/crud-react/pull/12
