### ISSUE TITLE
Verify if the URL input is empty

### ISSUE THREAD

**Issue by vitorsouzaalmeida** [vit0rr/crud-react#13]
Don't allow sending an empty URL

**Comment by vitorsouzaalmeida** [comment]
Pr: https://github.com/vit0rr/crud-react/pull/14

**Comment by hrutik7** [comment]
I like to work on this, will it be ok?

**Comment by vitorsouzaalmeida** [comment]
What did you think to solve this? Currently, I'm using a URL object to verify

**Comment by hrutik7** [comment]
yes , I checked that actually I  was thinking the same

**Comment by daniloab** [comment]
try to use yup + prepend-http to help you to make this validation

**Comment by fersilva16** [comment]
yup + prepend-http is worse than using URL
