### ISSUE TITLE
Create a GraphQL server

### ISSUE THREAD

**Issue by vitorsouzaalmeida** [vit0rr/crud-react#2]
- http server
- a post route with a graphql endpoint
- a graphql schema with at least a query type
- a query type with at least a field querying a simple value like query { version }

**Comment by vitorsouzaalmeida** [comment]
I'll write a post on my [blog](https://vitorsalmeida.com/) to understand and explain what I am learning about how REST API works

**Comment by daniloab** [comment]
go with graphql
