### ISSUE TITLE
Hide the edit input when unfocus

### ISSUE THREAD

**Issue by NicolasLopes7** [vit0rr/crud-react#5]
e.g: When I click on delete or outside the card the input is still being shown.

**Comment by NicolasLopes7** [comment]
https://user-images.githubusercontent.com/57234795/169629736-a0962838-b954-452b-88f0-9853fd8b6169.mov

**Comment by vitorsouzaalmeida** [comment]
Nice, I'll work to fix this

**Comment by vitorsouzaalmeida** [comment]
Solved on the last commit


![hideInput](https://user-images.githubusercontent.com/70543018/169666105-358892de-1a0a-4e6d-94f6-22900165af3e.gif)
